config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :podcasts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "podcasts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/podcast.rb
class Podcast < ApplicationRecord
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/podcasts_controller.rb
class PodcastsController < ApplicationController
  before_action :set_podcast, only: %i[ show edit update destroy ]

  # GET /podcasts or /podcasts.json
  def index
    @podcasts = Podcast.all
  end

  # GET /podcasts/1 or /podcasts/1.json
  def show
  end

  # GET /podcasts/new
  def new
    @podcast = Podcast.new
  end

  # GET /podcasts/1/edit
  def edit
  end

  # POST /podcasts or /podcasts.json
  def create
    @podcast = Podcast.new(podcast_params)

    respond_to do |format|
      if @podcast.save
        format.html { redirect_to podcast_url(@podcast), notice: "Podcast was successfully created." }
        format.json { render :show, status: :created, location: @podcast }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @podcast.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /podcasts/1 or /podcasts/1.json
  def update
    respond_to do |format|
      if @podcast.update(podcast_params)
        format.html { redirect_to podcast_url(@podcast), notice: "Podcast was successfully updated." }
        format.json { render :show, status: :ok, location: @podcast }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @podcast.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /podcasts/1 or /podcasts/1.json
  def destroy
    @podcast.destroy

    respond_to do |format|
      format.html { redirect_to podcasts_url, notice: "Podcast was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_podcast
      @podcast = Podcast.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def podcast_params
      params.require(:podcast).permit(:name, :descrption)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/podcasts_helper.rb
module PodcastsHelper
end

app/views/application/_error_fields.html.haml
- if f.errors.any?
  .alert.alert-error
    = pluralize(f.errors.count, "error")
    prohibited this user from being saved:
    %ul
      - f.errors.full_messages.each do |msg|
        %li= msg

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Resourcify
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload"
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_include_tag "application", "data-turbo-track": "reload", defer: true
  %body
    =render "shared/nav"
    %p.alert= alert
    %p.notice= notice
    %main.container.mx-auto.mt-28.px-5.flex
      = yield

app/views/podcasts/_form.html.haml
= form_with(model: podcast) do |form|
  - if podcast.errors.any?
    %div{:style => "color: red"}
      %h2
        = pluralize(podcast.errors.count, "error")
        prohibited this podcast from being saved:
      %ul
        - podcast.errors.each do |error|
          %li= error.full_message
  %div
    = form.label :name, style: "display: block"
    = form.text_field :name
  %div
    = form.label :descrption, style: "display: block"
    = form.text_area :descrption
  %div
    = form.submit

app/views/podcasts/_podcast.html.haml
%div{:id => "#{dom_id podcast}"}
  %p
    %strong Name:
    = podcast.name
  %p
    %strong Descrption:
    = podcast.descrption

app/views/podcasts/edit.html.haml
%h1 Editing podcast
= render "form", podcast: @podcast
%br/
%div
  = link_to "Show this podcast", @podcast
  |
  \#{link_to "Back to podcasts", podcasts_path}

app/views/podcasts/index.html.haml
%p{:style => "color: green"}= notice
%h1 Podcasts
#podcasts
  - @podcasts.each do |podcast|
    = render podcast
    %p
      = link_to "Show this podcast", podcast
= link_to "New podcast", new_podcast_path

app/views/podcasts/new.html.haml
%h1 New podcast
= render "form", podcast: @podcast
%br/
%div
  = link_to "Back to podcasts", podcasts_path

app/views/podcasts/show.html.haml
%p{:style => "color: green"}= notice
= render @podcast
%div
  = link_to "Edit this podcast", edit_podcast_path(@podcast)
  |
  \#{link_to "Back to podcasts", podcasts_path}
  
  \#{button_to "Destroy this podcast", @podcast, method: :delete}

app/views/shared/_nav.html.haml
%nav.bg-white.border-gray-200.px-2.sm:px-4.rounded.dark:bg-gray-800{:class => "py-2.5"}
  .container.flex.flex-wrap.justify-between.items-center.mx-auto
    %a.flex.items-center{:href => "https://flowbite.com"}
      %span.self-center.text-xl.font-semibold.whitespace-nowrap.dark:text-white Resourcify
    %button.inline-flex.items-center.p-2.ml-3.text-sm.text-gray-500.rounded-lg.md:hidden.hover:bg-gray-100.focus:outline-none.focus:ring-2.focus:ring-gray-200.dark:text-gray-400.dark:hover:bg-gray-700.dark:focus:ring-gray-600{"aria-controls" => "mobile-menu", "aria-expanded" => "false", "data-collapse-toggle" => "mobile-menu", :type => "button"}
      %span.sr-only Open main menu
      %svg.w-6.h-6{:fill => "currentColor", :viewbox => "0 0 20 20", :xmlns => "http://www.w3.org/2000/svg"}
        %path{"clip-rule" => "evenodd", :d => "M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z", "fill-rule" => "evenodd"}
      %svg.hidden.w-6.h-6{:fill => "currentColor", :viewbox => "0 0 20 20", :xmlns => "http://www.w3.org/2000/svg"}
        %path{"clip-rule" => "evenodd", :d => "M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z", "fill-rule" => "evenodd"}
    #mobile-menu.hidden.w-full.md:block.md:w-auto
      %ul.flex.flex-col.mt-4.md:flex-row.md:space-x-8.md:mt-0.md:text-sm.md:font-medium.items-center
        %li
          %a.block.py-2.pr-4.pl-3.text-white.bg-blue-700.rounded.md:bg-transparent.md:text-blue-700.md:p-0.dark:text-white{"aria-current" => "page", :href => "#"} Home
        %li
          %a.block.py-2.pr-4.pl-3.text-gray-700.border-b.border-gray-100.hover:bg-gray-50.md:hover:bg-transparent.md:border-0.md:hover:text-blue-700.md:p-0.dark:text-gray-400.md:dark:hover:text-white.dark:hover:bg-gray-700.dark:hover:text-white.md:dark:hover:bg-transparent.dark:border-gray-700{:href => "#"} About
        - if current_user
          %li
            %a.block.py-2.pr-4.pl-3.text-gray-700.border-b.border-gray-100.hover:bg-gray-50.md:hover:bg-transparent.md:border-0.md:hover:text-blue-700.md:p-0.dark:text-gray-400.md:dark:hover:text-white.dark:hover:bg-gray-700.dark:hover:text-white.md:dark:hover:bg-transparent.dark:border-gray-700{:href => "#"} Profile
          %li
            = button_to "Log out", destroy_user_session_path	, method: :delete, class: "p-2 block text-gray-300 bg-red-700 rounded"
        - else
          %li
            = link_to "Log in", new_user_session_path, class: "p-2 block text-gray-300 bg-gray-800 border-2 border-blue-700 rounded"
          %li
            = link_to "Sign up", new_user_registration_path, class: "p-2 block text-gray-300 bg-blue-700 rounded"

       